export const site = {
  name: 'Juan Lozano',
  brand: 'Jusell',
  email: 'juanlozanol@gmail.com',
  github: 'https://github.com/Jussell',
  linkedin: 'https://www.linkedin.com/in/juanlozanol/',
  behance: 'https://www.behance.net/juanlozanolamus'
};

export const copy = {
  en: {
    nav: { work: 'Work', about: 'About', contact: 'Contact' },
    eyebrow: 'Product designer · UX research · E-commerce',
    hero: 'Hi, I\'m Juan',
    heroText: 'A product designer focused on finding the insight behind the interface and turning it into measurable progress.',
    selectedWork: 'Selected work',
    viewProject: 'View case study',
    contactTitle: 'Have a product challenge?',
    contactText: 'Tell me what you are working on. I’m open to thoughtful collaborations and product teams that care about their users.',
    emailMe: 'Email me',
    contactNameLabel: 'Name',
    contactNamePlaceholder: 'Your name',
    contactEmailLabel: 'Email',
    contactEmailPlaceholder: 'your@email.com',
    contactMessageLabel: 'Message',
    contactMessagePlaceholder: 'Tell me about your project...',
    contactSubmit: 'Send message',
    contactSending: 'Sending...',
    contactSuccess: 'Message sent! I will get back to you soon.',
    contactError: 'Something went wrong. Please try again or email me directly.',
    aboutTitle: 'I’m Juan and I’m a designer who enjoys UX',
    aboutText: 'I am a Colombian industrial design graduate from Pontificia Universidad Javeriana, specialized in user-centered design. I have over 4 years of experience working in web design and UX/UI. I believe in consistent, systematic work to reach goals and achieve personal growth along the way.',
    cv: 'Download CV',
    inProgress: 'Case study in progress',
    back: 'Back to work',
    role: 'Role',
    duration: 'Duration',
    tools: 'Tools',
    previous: 'Previous project',
    next: 'Next project',
    language: 'ES'
  },
  es: {
    nav: { work: 'Proyectos', about: 'Perfil', contact: 'Contacto' },
    eyebrow: 'Product designer · Investigación UX · E-commerce',
    hero: 'Hola, soy Juan',
    heroText: 'Product designer enfocado en encontrar el insight detrás de la interfaz y convertirlo en progreso medible.',
    selectedWork: 'Proyectos seleccionados',
    viewProject: 'Ver caso de estudio',
    contactTitle: '¿Tienes un reto de producto?',
    contactText: 'Cuéntame en qué estás trabajando. Me interesan las colaboraciones cuidadosas y los equipos que diseñan pensando en sus usuarios.',
    emailMe: 'Escríbeme',
    contactNameLabel: 'Nombre',
    contactNamePlaceholder: 'Tu nombre',
    contactEmailLabel: 'Correo',
    contactEmailPlaceholder: 'tu@correo.com',
    contactMessageLabel: 'Mensaje',
    contactMessagePlaceholder: 'Cuéntame sobre tu proyecto...',
    contactSubmit: 'Enviar mensaje',
    contactSending: 'Enviando...',
    contactSuccess: '¡Mensaje enviado! Te responderé lo antes posible.',
    contactError: 'Algo salió mal. Inténtalo de nuevo o escríbeme directamente.',
    aboutTitle: 'Me llamo Juan y soy diseñador, disfrutando del UX',
    aboutText: 'Soy colombiano, estudié diseño industrial con un enfoque en diseño centrado en el usuario en la Universidad Javeriana. He trabajado en diseño web y UX/UI durante más de 4 años. Creo en el trabajo duro y sistemático para conseguir los objetivos y crecer como persona en el proceso.',
    cv: 'Descargar CV',
    inProgress: 'Caso de estudio en construcción',
    back: 'Volver a proyectos',
    role: 'Rol',
    duration: 'Duración',
    tools: 'Herramientas',
    previous: 'Proyecto anterior',
    next: 'Siguiente proyecto',
    language: 'EN'
  }
};

export type Locale = keyof typeof copy;
